services:
  - type: web
    name: ghl-mcp-server
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GHL_API_KEY
        sync: false  # This will need to be set in Render dashboard
      - key: GHL_BASE_URL
        value: https://services.leadconnectorhq.com
      - key: GHL_LOCATION_ID
        sync: false  # This will need to be set in Render dashboard
      - key: GHL_API_VERSION
        value: "2021-07-28"